
== Six Benefits of Reflexive Security

=== General
The six benefits can be explained with the acronym HEARTY (Human-centric, Elastic, Apt and
holistic, Resilient, Tailored, Dynamic).

=== Human-centric
Security is integrated and internalized as an aspect of everyone's work, and requires mind-share
within every employee. It is not an external responsibility enforced or required by a separate,
dedicated, security function.

=== Elastic
Growing maturity of a Reflexive Security approach could lead to achievement of formal ISMS
requirements, while being flexible enough to only target critical areas for maximum value based
on actual risks. Its principles allow scaling according to organizational risks and needs, preventing
permanent overhead in resource consumption.

=== Apt and holistic
Focused on business needs and responding to the actual risk context faced by the organization
when compared to traditional information security management, from business goals to operational
processes to humans, who often turn out to be the weakest link.

=== Resilient
Security no longer relies on a single security function, e.g. a single security department, but security
practices are integrated with business processes and embedded throughout the organization.
When compared to ISMS processes, an Reflexive Security approach often enables deeper security
involvement amongst personnel, resulting in more resilient security activities.

=== Tailored
Prioritized approach to provision stronger protection to core or more vulnerable processes over
those less exploitable. The traditional ISMS approach often applies the same set of controls across all
processes, leading to inefficient resource allocation.

=== Dynamic
The protection of business goals is performed by integrating security with business processes, often
down to the tactical level. This allows the organization to react faster and more effectively to threats
and incidents.
